# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f72bc44dd62115f48ae9c1e3113f1b8efe3576e40e1316497e76a66ae48a52efd52fe61913ea3b282bf8f734fae9239f4137c0976b44c87e2113f283e3fd3107

test:
  secret_key_base: 359f7de9b8f574b86f3288d2ef7731f665f5ab210cfef6a918f34d90648607c35f3bc532af3f7d71369d801936754fa9f9e6d2ded14db0def143cebd66663c50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
